### PR TITLE
adding_line

### PR DESCRIPTION
**Pull request by it-ces**

### CODE REVIEW

**Comment by it-trj** [comment]
your changes will be aproved, but please, add more documentations to the file. We need more specific problems to address the upcoming questiones. 
if you have doub'ts pleases contact me.

**Comment by it-ces** [comment]
yes, i'll add more information about.

**Review by it-trj — COMMENTED** [review]
yes, is very important for us your contribution-

**Comment by it-ces** [comment]
yes,  i'd like more information. but let me check a snippet of the random selection data.

**Comment by it-trj** [comment]
ok, but when you update the code?
give me a specific date.

**Comment by it-ces** [comment]
see, the last line, good bye.

**Pull request merged**
